version: '3.7'
services:
  db:
    image: 'mongo:5.0.17'
    ports:
      - '27017:27017'
    volumes:
      - './mongo:/data/db'

  client:
    image: bug-tracker
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./site:/site
    working_dir: /site
    build: ./site
    command: npm start
 