"""Added project ID to tasks and made projects types more strict

Revision ID: 4b41f11d72e1
Revises: d1d45d98796e
Create Date: 2022-09-08 14:12:21.999874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b41f11d72e1"
down_revision = "d1d45d98796e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects", "title", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("projects", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_foreign_key(None, "tasks", "projects", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "project_id")
    op.alter_column("projects", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "projects", "title", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
