"""Added projects

Revision ID: d1d45d98796e
Revises: 9faaaafcc69f
Create Date: 2022-09-07 14:09:08.680170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d45d98796e'
down_revision = '9faaaafcc69f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
